### ISSUE TITLE
defunct haproxy process

### ISSUE THREAD

**Issue by pvdputte** [haproxytechblog/ingress-controller-external-example#4]
I've been testing this for a while now and I notice there's always a defunct haproxy process with haproxy-ingress-controller as parent. Is this expected behaviour?

```
haproxy   268787       1  0 15:10 ?        00:00:00 /usr/local/bin/haproxy-ingress-controller --external --configmap=haproxy-ic/kubernetes-ingress --program=/usr/sbin/haproxy --ipv4-bind-address=0.0.0.0 --http-bind-port=80 &
haproxy   268868  268787  0 15:10 ?        00:00:00 [haproxy] <defunct>
haproxy   268870       1  0 15:10 ?        00:00:00 /usr/sbin/haproxy -f /tmp/haproxy-ingress/etc/haproxy.cfg
haproxy   268919  268870  1 15:10 ?        00:00:11 /usr/sbin/haproxy -sf 268871 -x sockpair@3 -f /tmp/haproxy-ingress/etc/haproxy.cfg
```

Could it be that it's because of config testing of some kind, using the haproxy binary, and haproxy-ingress-controller isn't reaping it?

As I've seen e.g. this in ps output as well
```
 /usr/sbin/haproxy -f /tmp/haproxy-ingress/etc/haproxy.cfg.1f5499b6-1541-4e86-95bd-4aa99d1104be -c
```

Which is a config check, but that one does disappear from the process list.

**Comment by NickMRamirez** [comment]
Hi @pvdputte,

This question looks better suited for https://github.com/haproxytech/kubernetes-ingress

**Comment by pvdputte** [comment]
Duly noted. Thanks!

**Comment by pvdputte** [comment]
Rather silent over there though https://github.com/haproxytech/kubernetes-ingress/issues/537

**Comment by NickMRamirez** [comment]
Sorry to hear there hasn't been any update on this. At least, it doesn't sound like there's a negative effect from these processes.

**Comment by pvdputte** [comment]
Well, the **stale** bot 'completed' the issue :slightly_smiling_face: 
Off to more pressing issues.
